# testdb url is jdbc:h2:mem:testdb
spring:
  h2:
    console:
      enabled: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      FAIL_ON_EMPTY_BEANS: false
    time-zone: UTC
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

logging:
  level:
    com.behnke.booking: DEBUG
